### ISSUE TITLE
Is it necessary to repeat code inside media queries?

### ISSUE THREAD

**Issue by fluxxus** [rstacruz/responsive-modular-scale.css#1]
I am maybe missing something obvious, but it seems to me that it is unnecessary to write multiple font size calculations for different sizes, when only one scale ratio is needed.

        root:{
     --ms-ratio: 1.15
     }
     @media (--ms-viewport-md){
     :root{
     --ms-ratio: 1.17
     }
     }
     @media (--ms-viewport-lg){
     :root{
     --ms-ratio: 1.2
     }
     }

**Comment by rstacruz** [comment]
Yes, this is necessary! This is what makes it responsive.

![image](https://user-images.githubusercontent.com/74385/51311267-78b9ef00-1a83-11e9-8dbb-2ed60f4367d7.png)

![image](https://user-images.githubusercontent.com/74385/51311281-7f486680-1a83-11e9-908a-72452c3415a1.png)

**Comment by rstacruz** [comment]
Oh and I forgot to add: in [PostCSS-cssnext](https://cssnext.github.io/), it's not possible to put CSS variables inside media queries like so:

```css
  /* Not allowed in postcss-cssnext */
 @media (--ms-viewport-md) {
   :root {
     --ms-ratio: 1.17
   }
 }
```

...since cssnext is deprecated now, maybe we can start exploring this again. [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables) supports this.

**Comment by rstacruz** [comment]
:( It looks like this case isn't supported by postcss-preset-env, at least if you plan to support IE11.

![image](https://user-images.githubusercontent.com/74385/57568329-6986f480-7418-11e9-9502-6613d7135206.png)

(IE11 supports `calc()` but not CSS variables.)
